#server:
#  port: 9008
#spring:
#  application:
#    name: codesocial-user #指定服务名
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.80.129:3306/codesocial_user?characterEncoding=UTF8
#    username: root
#    password: 123456
#  jpa:
#    database: MySQL
#    show-sql: true
#  redis:
#    host: 192.168.80.129
#  rabbitmq:
#    host: 192.168.80.129
#jwt:
#  config:
#    #密钥
#    key: codesocial
#    #过期时间，如果不配置则无期限，单位是毫秒
#    ttl: 86400000
##eureka:
##  client:
##    service-url:
##      defaultZone: http://localhost:6868/eureka
##  instance:
##    prefer-ip-address: true
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    #表示是否将自己注册到Eureka Server上，默认为true
#    registerWithEureka: false
#    #表示是否从Eureka Server上获取注册信息，默认为true
#    fetchRegistry: false
#    #Eureka Server的访问地址，服务注册和client获取服务注册
#    serviceUrl:
#      defaultZone: http://localhost:6868/eureka/

server:
  port: 9008
spring:
  application:
    name: tensquare-user #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.80.129:3306/codesocial_user?characterEncoding=UTF8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.80.129
  rabbitmq:
    host: 192.168.80.129
jwt:
  config:
    #密钥
    key: codesocial
    #过期时间，如果不配置则无期限，单位是毫秒
    ttl: 86400000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true