server:
  port: 9008
spring:
  application:
    name: codesocial-user #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.80.129:3306/codesocial_user?characterEncoding=UTF8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.80.129
  rabbitmq:
    host: 192.168.80.129