server:
  port: 9011
spring:
  application:
    name: codesocial-manager #指定服务名
eureka:
  client:
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
jwt:
  config:
    key: codesocial
zuul:
  routes:
    # 路由配置
    codesocial-gathering: #活动 名称可以随意取
      path: /gathering/** #配置请求URL的请求规则，get http://localhost:9005/gathering->http://localhost:9011/gathering/gathering
      serviceId: codesocial-gathering #指定Eureka注册中心中的服务id  微服的名称
    codesocial-article: #文章
      path: /article/** #配置请求URL的请求规则
      serviceId: codesocial-article #指定Eureka注册中心中的服务id
    codesocial-base: #基础
      path: /base/** #配置请求URL的请求规则
      serviceId: codesocial-base #指定Eureka注册中心中的服务id
    codesocial-friend: #交友
      path: /friend/** #配置请求URL的请求规则
      serviceId: codesocial-friend #指定Eureka注册中心中的服务id
    codesocial-qa: #问答
      path: /qa/** #配置请求URL的请求规则
      serviceId: codesocial-qa #指定Eureka注册中心中的服务id
    codesocial-recruit: #招聘
      path: /recruit/** #配置请求URL的请求规则
      serviceId: codesocial-recruit #指定Eureka注册中心中的服务id
    codesocial-spit: #吐槽
      path: /spit/** #配置请求URL的请求规则
      serviceId: codesocial-spit #指定Eureka注册中心中的服务id
    codesocial-user: #用户
      path: /user/** #配置请求URL的请求规则
      serviceId: codesocial-user #指定Eureka注册中心中的服务id